global:
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 30s
  repeat_interval: 1h
  receiver: jm-alerts
.
  routes:
  - match:
      job: prometheus
    receiver: jm-alerts
    repeat_interval: 1h
.
receivers:
- name: 'jm-alerts'
  email_configs:
