groups:

- name: server
  rules:

  - alert: high_load
    expr: node_load1 > 0.0
    for: 1s
    labels:
      severity: page
    annotations:
      summary: "Instance {{ $labels.instance }} under high load"
      description: "{{ $labels.instance }} of job {{ $labels.job }} is under high load."

- name: client
  rules:

  - alert: ClientInstanceDown
    expr: up{job="ubuntu1804-cAdvisor"} == 0
    for: 1s
    annotations:
      summary: "Instance {{ $labels.instance }} is down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} is down."
